### ISSUE TITLE
Fails to render text from Wikipedia

### ISSUE THREAD

**Issue by lorezyra** [tuanna-hsp/hexo-tag-wikipedia#2]
# Problem
Wikipedia tag only renders the link to the wiki page. No text in  blockquote is rendered. It appears that your example works just fine. But when using non-alphanumeric characters, the plugin fails.

# Markdown
```markdown

{% wikipedia title:Bernoulli%27s_principle wikiButton:true lang:en sentences:3 %}
{% wikipedia title:GitHub wikiButton:false lang:en sentences:3 %}
```
# Result
![Screen Shot 2021-06-06 at 20 11 38](https://user-images.githubusercontent.com/1673222/120922321-6f3c8a80-c703-11eb-942d-1aaaec935f2c.png)

# System Specs
- MacOS 11.4
- Hexo v5.4.0
- NodeJS 15.14.0
- hexo-tag-wikipedia: 1.0.0

# Request
Could you update this plugin so it will correctly handle escaped characters?
The Wiki page for Bernoulli's principle is: ```https://en.wikipedia.org/wiki/Bernoulli%27s_principle ```

**Comment by tuanna-hsp** [comment]
Thanks for reporting. 
I will have a look ASAP

**Comment by lorezyra** [comment]
Looks like an issue on https://github.com/tuanna-hsp/hexo-tag-wikipedia/blob/356d05b358883de460c13f98fafac74a8d01659e/index.js#L14 where the string isn't handled correctly.

**Comment by tuanna-hsp** [comment]
@lorezyra Fixed in `1.0.1`. 
https://www.npmjs.com/package/hexo-tag-wikipedia

Pls reinstall the plugin again.

(The problem was that, when the title contains special char, the generated `blockquote` element id also contains that special char too, which in turn make jQuery fails to reference it
https://github.com/tuanna-hsp/hexo-tag-wikipedia/blob/08ce44eb36d7b13c87a54d99fd8aa526d6fd1546/index.js#L29)

**Comment by tuanna-hsp** [comment]
Changes
https://github.com/tuanna-hsp/hexo-tag-wikipedia/commit/8d3f5a8910a2460ed0b76d8ffebba8eb9db870ee

**Comment by lorezyra** [comment]
Thanks! Confirmed working! 👍🏻
